// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Telechron.Host.Persistence;

#nullable disable

namespace Telechron.Host.Persistence.Migrations
{
    [DbContext(typeof(TelechronDbContext))]
    [Migration("20260723180033_ProjectToolchainAndLlmConnectionLinks")]
    partial class ProjectToolchainAndLlmConnectionLinks
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("Telechron.Host.Persistence.Entities.AgentSessionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("IssuedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MachineId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("RevokedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("SessionTokenHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MachineId");

                    b.HasIndex("SessionTokenHash")
                        .IsUnique();

                    b.ToTable("AgentSessions");
                });

            modelBuilder.Entity("Telechron.Host.Persistence.Entities.ArtifactEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ArtifactType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BlobRef")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("WorkflowRunId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("WorkflowRunId");

                    b.ToTable("Artifacts");
                });

            modelBuilder.Entity("Telechron.Host.Persistence.Entities.ConnectorEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ConfigurationJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeprecated")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ModuleId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SecretHandle")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("Connectors");
                });

            modelBuilder.Entity("Telechron.Host.Persistence.Entities.DesignDocumentEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId")
                        .IsUnique();

                    b.ToTable("DesignDocuments");
                });

            modelBuilder.Entity("Telechron.Host.Persistence.Entities.FindingEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("FailureClass")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FixStatus")
                        .HasColumnType("TEXT");

                    b.Property<string>("Fixability")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginFilePath")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RootCauseSignature")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("RunId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Severity")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("WorkflowRunId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("RunId");

                    b.ToTable("Findings");
                });

            modelBuilder.Entity("Telechron.Host.Persistence.Entities.FunctionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("InputArtifactTypesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeprecated")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ModuleId")
                        .HasColumnType("TEXT");

                    b.Property<int>("ModuleVersionMajor")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ModuleVersionMinor")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OutputArtifactTypesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Functions");
                });

            modelBuilder.Entity("Telechron.Host.Persistence.Entities.IntentPlanEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("AppliedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("CapabilityGapAnalysisJson")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("NaturalLanguageRequest")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PlanningPath")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProposedWorkflowIdsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RequiredModulesJson")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("IntentPlans");
                });

            modelBuilder.Entity("Telechron.Host.Persistence.Entities.LlmCallEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("CompletionTokens")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("EstimatedCostUsd")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("LlmConnectionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PromptRef")
                        .HasColumnType("TEXT");

                    b.Property<int>("PromptTokens")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Succeeded")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LlmConnectionId");

                    b.HasIndex("ProjectId");

                    b.ToTable("LlmCalls");
                });

            modelBuilder.Entity("Telechron.Host.Persistence.Entities.LlmConnectionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ConfigurationJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SecretHandle")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("LlmConnections");
                });

            modelBuilder.Entity("Telechron.Host.Persistence.Entities.MachineEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Hostname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsOnline")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LastHeartbeatUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("MachineFingerprint")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("RegisteredAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MachineFingerprint")
                        .IsUnique();

                    b.ToTable("Machines");
                });

            modelBuilder.Entity("Telechron.Host.Persistence.Entities.ModuleEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CapabilitiesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("InstalledAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceCodeRef")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TestCommand")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("VersionMajor")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VersionMinor")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VersionPatch")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Modules");
                });

            modelBuilder.Entity("Telechron.Host.Persistence.Entities.NotificationTargetEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("NotificationTargets");
                });

            modelBuilder.Entity("Telechron.Host.Persistence.Entities.PersonaEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AllowedConnectorIdsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AllowedSecretHandlesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AllowedToolsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AllowedWorkflowIdsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ApprovalPolicyJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ExecutionMode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("LlmConnectionId")
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxIterations")
                        .HasColumnType("INTEGER");

                    b.Property<long>("MaxLlmCostCents")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PromptTemplate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SystemPrompt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LlmConnectionId");

                    b.HasIndex("ProjectId");

                    b.ToTable("Personas");
                });

            modelBuilder.Entity("Telechron.Host.Persistence.Entities.ProjectEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("LlmConnectionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("TEXT");

                    b.Property<int>("RepairPolicy")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RootPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ToolchainId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LlmConnectionId");

                    b.HasIndex("OwnerUserId");

                    b.HasIndex("ToolchainId");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("Telechron.Host.Persistence.Entities.ProjectMembershipEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("UserId", "ProjectId")
                        .IsUnique();

                    b.ToTable("ProjectMemberships");
                });

            modelBuilder.Entity("Telechron.Host.Persistence.Entities.RepairAttemptEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ApprovalDecision")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("ApproverUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CommitReference")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("PatchDiff")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProvenanceRecordJson")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ResultingArtifactId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SnapshotRef")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VerifyResultJson")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ApproverUserId");

                    b.HasIndex("ResultingArtifactId");

                    b.ToTable("RepairAttempts");
                });

            modelBuilder.Entity("Telechron.Host.Persistence.Entities.RepairAttemptFindingEntity", b =>
                {
                    b.Property<Guid>("RepairAttemptId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FindingId")
                        .HasColumnType("TEXT");

                    b.HasKey("RepairAttemptId", "FindingId");

                    b.HasIndex("FindingId");

                    b.ToTable("RepairAttemptFindings");
                });

            modelBuilder.Entity("Telechron.Host.Persistence.Entities.RequirementEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("CurrentRevisionNumber")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("DesignDocumentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RequirementId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DesignDocumentId", "RequirementId")
                        .IsUnique();

                    b.ToTable("Requirements");
                });

            modelBuilder.Entity("Telechron.Host.Persistence.Entities.RequirementRevisionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ChangeReason")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ChangedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RequirementId")
                        .HasColumnType("TEXT");

                    b.Property<int>("RevisionNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ChangedByUserId");

                    b.HasIndex("RequirementId", "RevisionNumber")
                        .IsUnique();

                    b.ToTable("RequirementRevisions");
                });

            modelBuilder.Entity("Telechron.Host.Persistence.Entities.ResourceEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ExclusiveGroup")
                        .HasColumnType("TEXT");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MachineId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExclusiveGroup");

                    b.HasIndex("MachineId");

                    b.ToTable("Resources");
                });

            modelBuilder.Entity("Telechron.Host.Persistence.Entities.RunEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LastHeartbeatUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("LogsRef")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("MachineId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("StartedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SuiteResultsJson")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MachineId");

                    b.HasIndex("ProjectId");

                    b.ToTable("Runs");
                });

            modelBuilder.Entity("Telechron.Host.Persistence.Entities.SecretEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("EncryptedValue")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<string>("EncryptionKeyId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Handle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("RevokedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Handle")
                        .IsUnique();

                    b.HasIndex("ProjectId");

                    b.ToTable("Secrets");
                });

            modelBuilder.Entity("Telechron.Host.Persistence.Entities.ToolchainEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("BuildCommand")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DeployCommand")
                        .HasColumnType("TEXT");

                    b.Property<string>("EnvironmentRequirementsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ExportCommand")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ModuleId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TestCommand")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VerifyCommand")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Toolchains");
                });

            modelBuilder.Entity("Telechron.Host.Persistence.Entities.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AuthCredentialHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Telechron.Host.Persistence.Entities.WorkflowEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DefinitionJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("FailurePolicy")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("Workflows");
                });

            modelBuilder.Entity("Telechron.Host.Persistence.Entities.WorkflowRunEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DefinitionSnapshotJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("StartedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("WorkflowId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("WorkflowId");

                    b.ToTable("WorkflowRuns");
                });

            modelBuilder.Entity("Telechron.Host.Persistence.Entities.AgentSessionEntity", b =>
                {
                    b.HasOne("Telechron.Host.Persistence.Entities.MachineEntity", "Machine")
                        .WithMany()
                        .HasForeignKey("MachineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Machine");
                });

            modelBuilder.Entity("Telechron.Host.Persistence.Entities.ArtifactEntity", b =>
                {
                    b.HasOne("Telechron.Host.Persistence.Entities.WorkflowRunEntity", "WorkflowRun")
                        .WithMany()
                        .HasForeignKey("WorkflowRunId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("WorkflowRun");
                });

            modelBuilder.Entity("Telechron.Host.Persistence.Entities.ConnectorEntity", b =>
                {
                    b.HasOne("Telechron.Host.Persistence.Entities.ProjectEntity", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Telechron.Host.Persistence.Entities.DesignDocumentEntity", b =>
                {
                    b.HasOne("Telechron.Host.Persistence.Entities.ProjectEntity", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Telechron.Host.Persistence.Entities.FindingEntity", b =>
                {
                    b.HasOne("Telechron.Host.Persistence.Entities.ProjectEntity", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Telechron.Host.Persistence.Entities.RunEntity", "Run")
                        .WithMany()
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Project");

                    b.Navigation("Run");
                });

            modelBuilder.Entity("Telechron.Host.Persistence.Entities.IntentPlanEntity", b =>
                {
                    b.HasOne("Telechron.Host.Persistence.Entities.ProjectEntity", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Telechron.Host.Persistence.Entities.LlmCallEntity", b =>
                {
                    b.HasOne("Telechron.Host.Persistence.Entities.LlmConnectionEntity", "LlmConnection")
                        .WithMany()
                        .HasForeignKey("LlmConnectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Telechron.Host.Persistence.Entities.ProjectEntity", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("LlmConnection");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Telechron.Host.Persistence.Entities.NotificationTargetEntity", b =>
                {
                    b.HasOne("Telechron.Host.Persistence.Entities.UserEntity", "User")
                        .WithMany("NotificationTargets")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Telechron.Host.Persistence.Entities.PersonaEntity", b =>
                {
                    b.HasOne("Telechron.Host.Persistence.Entities.LlmConnectionEntity", "LlmConnection")
                        .WithMany()
                        .HasForeignKey("LlmConnectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Telechron.Host.Persistence.Entities.ProjectEntity", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LlmConnection");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Telechron.Host.Persistence.Entities.ProjectEntity", b =>
                {
                    b.HasOne("Telechron.Host.Persistence.Entities.LlmConnectionEntity", "LlmConnection")
                        .WithMany()
                        .HasForeignKey("LlmConnectionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Telechron.Host.Persistence.Entities.UserEntity", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Telechron.Host.Persistence.Entities.ToolchainEntity", "Toolchain")
                        .WithMany()
                        .HasForeignKey("ToolchainId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("LlmConnection");

                    b.Navigation("Owner");

                    b.Navigation("Toolchain");
                });

            modelBuilder.Entity("Telechron.Host.Persistence.Entities.ProjectMembershipEntity", b =>
                {
                    b.HasOne("Telechron.Host.Persistence.Entities.ProjectEntity", "Project")
                        .WithMany("Memberships")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Telechron.Host.Persistence.Entities.UserEntity", "User")
                        .WithMany("Memberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Telechron.Host.Persistence.Entities.RepairAttemptEntity", b =>
                {
                    b.HasOne("Telechron.Host.Persistence.Entities.UserEntity", "Approver")
                        .WithMany()
                        .HasForeignKey("ApproverUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Telechron.Host.Persistence.Entities.ArtifactEntity", "ResultingArtifact")
                        .WithMany()
                        .HasForeignKey("ResultingArtifactId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Approver");

                    b.Navigation("ResultingArtifact");
                });

            modelBuilder.Entity("Telechron.Host.Persistence.Entities.RepairAttemptFindingEntity", b =>
                {
                    b.HasOne("Telechron.Host.Persistence.Entities.FindingEntity", "Finding")
                        .WithMany()
                        .HasForeignKey("FindingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Telechron.Host.Persistence.Entities.RepairAttemptEntity", "RepairAttempt")
                        .WithMany("FindingLinks")
                        .HasForeignKey("RepairAttemptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Finding");

                    b.Navigation("RepairAttempt");
                });

            modelBuilder.Entity("Telechron.Host.Persistence.Entities.RequirementEntity", b =>
                {
                    b.HasOne("Telechron.Host.Persistence.Entities.DesignDocumentEntity", "DesignDocument")
                        .WithMany()
                        .HasForeignKey("DesignDocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DesignDocument");
                });

            modelBuilder.Entity("Telechron.Host.Persistence.Entities.RequirementRevisionEntity", b =>
                {
                    b.HasOne("Telechron.Host.Persistence.Entities.UserEntity", "ChangedByUser")
                        .WithMany()
                        .HasForeignKey("ChangedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Telechron.Host.Persistence.Entities.RequirementEntity", "Requirement")
                        .WithMany()
                        .HasForeignKey("RequirementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChangedByUser");

                    b.Navigation("Requirement");
                });

            modelBuilder.Entity("Telechron.Host.Persistence.Entities.ResourceEntity", b =>
                {
                    b.HasOne("Telechron.Host.Persistence.Entities.MachineEntity", "Machine")
                        .WithMany()
                        .HasForeignKey("MachineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Machine");
                });

            modelBuilder.Entity("Telechron.Host.Persistence.Entities.RunEntity", b =>
                {
                    b.HasOne("Telechron.Host.Persistence.Entities.MachineEntity", "Machine")
                        .WithMany()
                        .HasForeignKey("MachineId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Telechron.Host.Persistence.Entities.ProjectEntity", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Machine");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Telechron.Host.Persistence.Entities.SecretEntity", b =>
                {
                    b.HasOne("Telechron.Host.Persistence.Entities.ProjectEntity", "Project")
                        .WithMany("Secrets")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Telechron.Host.Persistence.Entities.WorkflowEntity", b =>
                {
                    b.HasOne("Telechron.Host.Persistence.Entities.ProjectEntity", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Telechron.Host.Persistence.Entities.WorkflowRunEntity", b =>
                {
                    b.HasOne("Telechron.Host.Persistence.Entities.WorkflowEntity", "Workflow")
                        .WithMany()
                        .HasForeignKey("WorkflowId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Workflow");
                });

            modelBuilder.Entity("Telechron.Host.Persistence.Entities.ProjectEntity", b =>
                {
                    b.Navigation("Memberships");

                    b.Navigation("Secrets");
                });

            modelBuilder.Entity("Telechron.Host.Persistence.Entities.RepairAttemptEntity", b =>
                {
                    b.Navigation("FindingLinks");
                });

            modelBuilder.Entity("Telechron.Host.Persistence.Entities.UserEntity", b =>
                {
                    b.Navigation("Memberships");

                    b.Navigation("NotificationTargets");
                });
#pragma warning restore 612, 618
        }
    }
}
