namespace Telechron.Host.Agents.Mtls;

// R-SEC2: paths to the dev CA + Host server cert generated by
// scripts/Generate-DevCerts.ps1. Production deployments swap these for a
// real CA/cert-issuance pipeline behind the same shape.
public sealed class MtlsOptions
{
    public string CaCertPath { get; set; } = string.Empty;
    public string HostCertPfxPath { get; set; } = string.Empty;
    public string HostCertPassword { get; set; } = string.Empty;
}
