// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Telechron.Host.Security.Audit;

#nullable disable

namespace Telechron.Host.Security.Audit.Migrations
{
    [DbContext(typeof(AuditDbContext))]
    [Migration("20260722193956_InitialAuditLog")]
    partial class InitialAuditLog
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("Telechron.Host.Security.Audit.AuditEventEntity", b =>
                {
                    b.Property<long>("Sequence")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DetailJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("PriorHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RecordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Sequence");

                    b.HasIndex("OccurredAtUtc");

                    b.HasIndex("ProjectId");

                    b.ToTable("AuditEvents");
                });
#pragma warning restore 612, 618
        }
    }
}
